In [16]:
import numpy as np
# numpy create syntax
# numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)


# 1 d array 
d1 = np.array([1,2,3,9,6,56,5,23,565],ndmin=3)  # 1 block 1 row and 5 columns
print(d1)

# 2d array
d2 = np.array([[1,3],[5,6]])
print(d2)

[[[  1   2   3   9   6  56   5  23 565]]]
[[1 3]
 [5 6]]


In [10]:
# we can get the how much dimension the array is by 
print(d1.ndim)
print(d2.ndim)

print(d1.nbytes)

3
2
12


In [9]:
# SHAPE of the array
print(d1.shape)
print(d2.shape)

(1, 1, 3)
(2, 2)


In [ ]:
# accessing element is basically the row and column
d1[0,0,2]
d1[0,0,0::2]  # start end step

array([  1,   3,   6,   5, 565])

In [20]:
d2[:,1]

array([3, 6])

In [21]:
# Initializing 
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,2,2)) # np.ones()

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [25]:
np.full((2,3),5) # shape of the array and the value

array([[5, 5, 5],
       [5, 5, 5]])

In [38]:
a = np.ones((2,3))
print(a)
a[0, 0:] = [1,2,3] 
print(a)

b = np.array([[2,3],[4,6],[1,3]])
print(b)
np.matmul(a,b)
print(b.size)

print(a+10)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 2. 3.]
 [1. 1. 1.]]
[[2 3]
 [4 6]
 [1 3]]
6
[[11. 12. 13.]
 [11. 11. 11.]]


In [47]:
# Challenge
# 🎯 Mini Challenge (Practice):
# Create a 1D NumPy array of numbers from 1 to 10.

# Multiply all numbers by 3.

# Extract only the even numbers using slicing or masking.

# Create a 2D NumPy array (3x3) with random numbers between 0 and 1.

arr = np.arange(0,11,1)
print(arr)

print(arr * 3)

print(arr[0::2])

print(arr[arr %2 ==0])

ar1 = np.random.rand(3,3)
print(ar1)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  3  6  9 12 15 18 21 24 27 30]
[ 0  2  4  6  8 10]
[ 0  2  4  6  8 10]
[[0.92305087 0.28565251 0.6953608 ]
 [0.31572536 0.4111602  0.19796612]
 [0.32707898 0.23679122 0.1209438 ]]
